### ISSUE TITLE
Strange behaviour when changing between Sign In and Sign Up states

### ISSUE THREAD

**Issue by PolGuixe** [studiointeract/accounts-ui#43] opened 2016-05-12 15:56 UTC
When I start filling the fields in the `loginForm` in `Sign In` state, but then I realise that I am creating a new user, hence I change to `Sign Up` state, when I submit the form, for some reason it is not working. 

See: http://recordit.co/prX8u4YmWI

I don't know how to classify this, but I guess is a bug as it is a behaviour that I would expect.

**Comment by timbrandin** [comment] 2016-05-24 20:45
Was there any error in the terminal at the same time? Otherwise I believe this could be a UI issue.

**Comment by danpilat** [comment] 2016-05-25 19:10
I believe this is because you're using the same component (Accounts.ui.LoginForm) for both login and register. I get the same behaviour - if you actually register a user AFTER you click "Register" the first time, it should work. 

It'd be great if we could get another default component for sign-up already packaged in accounts-ui (one that would be extended to have a password confirmation field for example).

**Comment by PolGuixe** [comment] 2016-05-31 20:50
@timbrandin there is no error in the terminal. 

@danpilat I am using the same component. Changing between `Sign In` ans `Sign Up` is just changing the state of the component. But I don't understand why when starting from `Sign In`, the  fields entered give an error when moving to the  `Sign Up` state? @timbrandin  any idea?

**Comment by timbrandin** [comment] 2016-12-18 13:29
This seems strange, could it be caused by accounts-basic maybe?

**Comment by timbrandin** [comment] 2016-12-18 15:07
This should be resolved in 1.2.11, and this seems like a duplicate of #61

**Closed by timbrandin** 2016-12-18 15:07 UTC
